language: python
python:
  - "2.7"
cache: apt
before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get install qgis libqt4-dev python-qt4 python-qt4-dev python-qgis
install: "pip install -r travis_requirements.txt"
script: nosetests